// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "UYX5XTB5RZ/moc_lpanelaffinetransforms.cpp"
#include "UYX5XTB5RZ/moc_lpanelconvolution.cpp"
